function [s,s_udg] = source_ns3d(pg,udg,param,time)
%SOURCE_NS3D
%    [S,S_UDG] = SOURCE_NS3D(PG,UDG,PARAM,TIME)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    16-Dec-2019 16:05:11
[ng,nc] = size(udg);
nch = 5;
nd = 3;
one = ones(ng,1);
param2 = param{2};
u1 = udg(:,1);
u2 = udg(:,2);
u3 = udg(:,3);
x1 = pg(:,1);
x2 = pg(:,2);
zero = zeros(ng,1);
t2 = param2.^2;
s = [zero;param2.*u3.*2.0+t2.*u1.*x1;param2.*u2.*-2.0+t2.*u1.*x2;zero;zero];
if nargout > 1
    s_udg = [zero;one.*t2.*x1;one.*t2.*x2;zero;zero;zero;zero;one.*param2.*-2.0;zero;zero;zero;one.*param2.*2.0;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero];
end
s = reshape(s,ng,nch);
s_udg = reshape(s_udg,ng,nch,nc);
