function [s,s_udg] = source_polarns2d(pg,udg,param,time)
%SOURCE_POLARNS2D
%    [S,S_UDG] = SOURCE_POLARNS2D(PG,UDG,PARAM,TIME)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    12-Dec-2019 17:55:46
[ng,nc] = size(udg);
nch = 4;
nd = 2;
zero = zeros(ng,1);
s = [zero;zero;zero;zero];
if nargout > 1
    s_udg = [zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero];
end
s = reshape(s,ng,nch);
s_udg = reshape(s_udg,ng,nch,nc);
