function [s,s_udg] = tmp(in1,in2,in3,time,in5)
%TMP
%    [S,S_UDG] = TMP(IN1,IN2,IN3,TIME,IN5)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    12-Dec-2019 17:55:46

zero = in5(:,1);
s = [zero;zero;zero;zero];
if nargout > 1
    s_udg = [zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero];
end
