function [s,s_udg] = source2d(p,udg,param1,time)
%SOURCE2D
%    [S,S_UDG] = SOURCE2D(P,UDG,PARAM1,TIME)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    06-Sep-2023 15:41:53
[ng,nc] = size(udg);
nch = 1;
nd = 2;
zero = zeros(ng,1);
s = zero;
if nargout > 1
    s_udg = [zero;zero;zero];
end
s = reshape(s,ng,nch);
s_udg = reshape(s_udg,ng,nch,nc);
