function [s,s_udg] = source_ns2d(pg,udg,param,time)
%SOURCE_NS2D
%    [S,S_UDG] = SOURCE_NS2D(PG,UDG,PARAM,TIME)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    14-Dec-2019 08:15:24
[ng,nc] = size(udg);
nch = 4;
nd = 2;
one = ones(ng,1);
param2 = param{2};
u2 = udg(:,2);
u3 = udg(:,3);
zero = zeros(ng,1);
s = [zero;param2.*u3;-param2.*u2;zero];
if nargout > 1
    s_udg = [zero;zero;zero;zero;zero;zero;-one.*param2;zero;zero;one.*param2;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero];
end
s = reshape(s,ng,nch);
s_udg = reshape(s_udg,ng,nch,nc);
