function [s,s_udg] = source2d(p,udg,param1,time)
%SOURCE2D
%    [S,S_UDG] = SOURCE2D(P,UDG,PARAM1,TIME)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    06-Sep-2023 18:03:10
[ng,nc] = size(udg);
nch = 1;
nd = 2;
one = ones(ng,1);
u1 = udg(:,1);
x1 = p(:,1);
zero = zeros(ng,1);
s = u1.*x1.*(5.0./2.0);
if nargout > 1
    s_udg = [one.*x1.*(5.0./2.0);zero;zero];
end

s = reshape(s,ng,nch);
s_udg = reshape(s_udg,ng,nch,nc);
